[workspace]
channels = ["conda-forge"]
name = "pycppad"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
libboost-devel = "*"
cppad = "*"
cmake = "*"
pkg-config = "*"
ninja = "*"
cxx-compiler = "*"
clangxx = "*"
doxygen = "*"
python = "*"

[activation]
scripts = ["development/scripts/pixi/activation.sh"]

[tasks]
configure = { cmd = [
    "cmake",
    "-G",
    "Ninja",
    "-B",
    "build",
    "-S",
    ".",
    "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
    "-DBUILD_WITH_CPPAD_CODEGEN_BINDINGS=$BUILD_WITH_CPPAD_CODEGEN_BINDINGS=OFF",
    "-DWITH_BOOST_PY_BINDING=$WITH_BOOST_PY_BINDING=OFF",

] }
build = { cmd = "cmake --build build --target all", depends-on = ["configure"] }
clean = { cmd = "rm -rf build" }

# add boost python binding
[feature.boostpybinding]
dependencies = { libboost-python-devel = "*", eigenpy = "*" }
activation = { env = { WITH_BOOST_PY_BINDING = "ON", PYTHONPATH = "$PYTHONPATH:${PIXI_PROJECT_ROOT}/build/python" } }

# add python binding for code generation
[feature.cppadcg-binding]
dependencies = { cppadcodegen = "*" }
activation = { env = { BUILD_WITH_CPPAD_CODEGEN_BINDINGS = "ON" } }

[environments]
default = { features = ["boostpybinding"] }
cppadcg-binding = { features = ["boostpybinding", "cppadcg-binding"] }
