[workspace]
channels = ["conda-forge"]
name = "pycppad"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
libboost-devel = "*"
cppad = "*"
cppadcodegen = "*"
cmake = "*"
pkg-config = "*"
ninja = "*"
cxx-compiler = "*"
clangxx = "*"
doxygen = "*"
python = "*"

[activation]
scripts = ["development/scripts/pixi/activation.sh"]

[tasks]
configure = { cmd = [
    "cmake",
    "-G",
    "Ninja",
    "-B",
    "build",
    "-S",
    ".",
    "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
    "-DWITH_BOOST_PY_BINDING=$WITH_BOOST_PY_BINDING",

] }
build = { cmd = "cmake --build build --target all", depends-on = ["configure"] }
clean = { cmd = "rm -rf build" }

[environments]
default = []
